import type { Nature } from "@/types/pokemon";

// Extract from TypeBadge.tsx and NatureBadge.tsx
export const POKEMON_THEME = {
  types: {
    fire: { bg: "#F08030", text: "white", border: "#9C531F" },
    water: { bg: "#6890F0", text: "white", border: "#445E9C" },
    grass: { bg: "#78C850", text: "white", border: "#4E8234" },
    electric: { bg: "#F8D030", text: "gray-800", border: "#A1871F" },
    ice: { bg: "#98D8D8", text: "gray-800", border: "#638D8D" },
    fighting: { bg: "#C03028", text: "white", border: "#7D1F1A" },
    poison: { bg: "#A040A0", text: "white", border: "#682A68" },
    ground: { bg: "#E0C068", text: "gray-800", border: "#927D44" },
    flying: { bg: "#A890F0", text: "white", border: "#6D5E9C" },
    psychic: { bg: "#F85888", text: "white", border: "#A13959" },
    bug: { bg: "#A8B820", text: "white", border: "#6D7815" },
    rock: { bg: "#B8A038", text: "white", border: "#786824" },
    ghost: { bg: "#705898", text: "white", border: "#493963" },
    dragon: { bg: "#7038F8", text: "white", border: "#4924A1" },
    dark: { bg: "#705848", text: "white", border: "#49392F" },
    steel: { bg: "#B8B8D0", text: "gray-800", border: "#787887" },
    fairy: { bg: "#EE99AC", text: "gray-800", border: "#9B6470" },
    normal: { bg: "#A8A878", text: "white", border: "#6D6D4E" },
  },
  statuses: {
    healthy: { bg: "#78C850", text: "white", border: "#4E8234" },
    poisoned: { bg: "#A040A0", text: "white", border: "#682A68" },
    burned: { bg: "#F08030", text: "white", border: "#9C531F" },
    frozen: { bg: "#98D8D8", text: "gray-800", border: "#638D8D" },
    paralyzed: { bg: "#F8D030", text: "gray-800", border: "#A1871F" },
    asleep: { bg: "#A890F0", text: "white", border: "#6D5E9C" },
  },

  natures: {
    Adamant: { boost: "atk", reduce: "spa" },
    Bashful: { boost: null, reduce: null },
    Bold: { boost: "def", reduce: "atk" },
    Brave: { boost: "atk", reduce: "spe" },
    Calm: { boost: "spd", reduce: "atk" },
    Careful: { boost: "spd", reduce: "spa" },
    Docile: { boost: null, reduce: null },
    Gentle: { boost: "spd", reduce: "def" },
    Hardy: { boost: null, reduce: null },
    Hasty: { boost: "spe", reduce: "def" },
    Impish: { boost: "def", reduce: "spa" },
    Jolly: { boost: "spe", reduce: "spa" },
    Lax: { boost: "def", reduce: "spd" },
    Lonely: { boost: "atk", reduce: "def" },
    Mild: { boost: "spa", reduce: "def" },
    Modest: { boost: "spa", reduce: "atk" },
    Naive: { boost: "spe", reduce: "spd" },
    Naughty: { boost: "atk", reduce: "spd" },
    Quiet: { boost: "spa", reduce: "spe" },
    Quirky: { boost: null, reduce: null },
    Rash: { boost: "spa", reduce: "spd" },
    Relaxed: { boost: "def", reduce: "spe" },
    Sassy: { boost: "spd", reduce: "spe" },
    Serious: { boost: null, reduce: null },
    Timid: { boost: "spe", reduce: "atk" },
  } as Record<Nature, { boost: string | null; reduce: string | null }>,
} as const;
